spring:
  application:
    name: client-service
server:  port: ${PORT:8901}
eureka:
  client:
    service-url:      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}  
management:
   context-path: /application
   port: ${PORT}
   security:
      enabled: false
   health:
      diskspace:
         enable: false
   endpoints:
      web:
         exposure:
            include: /*
spring:
   security:
      user:
         name: user
         password: password  
