server :
  port : ${PORT:8761}
eureka :
  client:    register-with-eureka: false
    fetchRegistry: false 
spring:
   rabbitmq:
      host: localhost
      port: 5672
      username: guest   
      password: guest
   datasource:
      driverClassName : org.mariadb.jdbc.Driver
      url : jdbc:mariadb://localhost:33301      
      username : root
      password : g@KgUnHhcYUYu7.
  