server :
  port : ${PORT:8761}
eureka :
  client:    register-with-eureka: false
    fetchRegistry: false 
spring:
   rabbitmq:
      host: localhost
      port: ${server.port}
      username: user
      password: password
      